### ISSUE TITLE
wslview open file by absolute path failed

### ISSUE THREAD

**Issue by panjie** [wslutilities/wslu#118]
I use wslview to open a file by absolute path failed with the following error message:

```
$ wslview /home/panjie/temp/aaa.docx

Start : 由于出现以下错误，无法运行此命令: 系统找不到指定的文件。。
所在位置 行:1 字符: 1
+ Start "/home/panjie/temp/aaa.docx"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process]，InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

The first two lines are in Chinese which means Start is error becuase system could not found specified file.

While using relative path is OK, such as ` wslview ./temp/aaa.docx`.

The environment I am using:
* Windows 10 2004 19041.208 
* WSL2 Ubuntu 18.04

**Comment by patrick330602** [comment]
Thank you for the feedback. This is already fixed in wslu 3.1 that is going to release really soon. The update for Ubuntu will take a longer time, say longer than a month FYI.

**Comment by panjie** [comment]
I noticed that the the corresponding code in PR #115 is still buggy because the following line should be added to between line 55 and 56.
```
             properfile_full_path="$(readlink -f "${lname//file:\/\//}")"   
```

**Comment by patrick330602** [comment]
Hi @panjie, 

Thank you for the heads up. I will try to fix the issue in the coming update wslu 3.1.1.
